
require 'rubygems'
require 'ffi'
require 'rake/clean'
require File.expand_path('../../lib/libcouchbase/ext/tasks', __FILE__)


Dir.chdir File.expand_path("../../", __FILE__)


task :default => :libcouchbase

desc "Compile libcouchbase from submodule"
if FFI::Platform.windows?
    task :libcouchbase => ["ext/bin/libcouchbase.#{FFI::Platform::LIBSUFFIX}"]
    CLOBBER.include("ext/bin/libcouchbase.#{FFI::Platform::LIBSUFFIX}")
else
    task :libcouchbase => ["ext/libcouchbase/build/lib/libcouchbase_libuv.#{FFI::Platform::LIBSUFFIX}"]
    CLOBBER.include("ext/libcouchbase/build/lib/libcouchbase_libuv.#{FFI::Platform::LIBSUFFIX}")
end
